#分库分表
spring:
  shardingsphere:
    datasource:
      names: ds3, ds4, ds5
      ds3:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds3?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
        username: root
        password: root
        maxPoolSize: 50
        minPoolSize: 1
      ds4:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds4?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
        username: root
        password: root
        maxPoolSize: 50
        minPoolSize: 1
      ds5:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds5?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
        username: root
        password: root
        maxPoolSize: 50
        minPoolSize: 1
    sharding:
      default-database-strategy:
        inline:
          sharding-column: user_id
          algorithm-expression: ds$->{user_id % 3 + 3}
      binding-tables: health_record,health_task
      broadcast-tables: health_level

      tables:
        health_record:
          actual-data-nodes: ds$->{3..5}.health_record$->{0..2}
          table-strategy:
            inline:
              sharding-column: record_id
              algorithm-expression: health_record$->{record_id % 3}
          key-generator:
            type: SNOWFLAKE
            column: record_id
            props:
              worker:
                id: 33
        health_task:
          actual-data-nodes: ds$->{3..5}.health_task$->{0..2}
          table-strategy:
            inline:
              sharding-column: record_id
              algorithm-expression: health_task$->{record_id % 3}
          key-generator:
            type: SNOWFLAKE
            column: task_id
            props:
              worker:
                id: 33
    props:
      sql.show: true



