# 数据脱敏
# 问题: 明文列没有存储
spring:
  shardingsphere:
    datasource:
      names: dsencrypt
      dsencrypt:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/dsencrypt?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
        username: root
        password: root
        maxPoolSize: 50
        minPoolSize: 1
    props:
      sql.show: true
    encrypt:
      encryptors:
        name_encryptor:
          type: aes
          qualified-columns: encrypt_user.user_name
          assistedQueryColumns: encrypt_user.user_name_plain
          props:
            aes.key.value: 123456
        pwd_encryptor:
          type: md5
          qualified-columns: encrypt_user.pwd
      tables:
        encrypt_user:
          columns:
            user_name:
              plainColumn: user_name_plain
              cipherColumn: user_name
              encryptor: name_encryptor
            pwd:
              cipherColumn: pwd
              encryptor: pwd_encryptor

#    props:
#      sql.show: true
#      query:
#        with:
#        cipher:
#          comlum: true

